manifest_file: tfrecords/manifests/das_low_prob_balanced_eval_manifest.txt
output_file_prefix: tfrecords/das_low_prob_balanced/eval
input_width: 288
input_height: 695
num_shards: 1
min_val: -2.1995878
max_val: 2.1995878