manifest_file: tfrecords/manifests/das_low_prob_balanced_train_manifest.txt
output_file_prefix: tfrecords/das_low_prob_balanced/train
input_width: 288
input_height: 695
num_shards: 1
min_val: -0.10575
max_val: 0.10575
# 2nd and 98th percentile of the dataset